// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Normalized `ATTITUDE`.
 */
export type Attitude = { time_boot_ms: number, roll_deg: number, pitch_deg: number, yaw_deg: number, roll_speed_deg_s: number, pitch_speed_deg_s: number, yaw_speed_deg_s: number, };
