// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Decoded `MAV_MODE_FLAG` bitmap.
 */
export type BaseMode = { custom_mode_enabled: boolean, test_enabled: boolean, auto_enabled: boolean, guided_enabled: boolean, stabilize_enabled: boolean, hil_enabled: boolean, manual_input_enabled: boolean, safety_armed: boolean, };
