// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Normalized `BATTERY_STATUS`.
 */
export type BatteryStatus = { battery_id: number, 
/**
 * Per-cell voltages in millivolts.
 */
voltage_cells_mv: Array<number>, current_ma: number, 
/**
 * 0–100, `None` when unknown.
 */
remaining_percent: number | null, 
/**
 * Degrees Celsius; `None` when the FC reports unknown.
 */
temperature_deg_c: number | null, };
