// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { GeoPoint } from "./GeoPoint";

/**
 * A cloverleaf (or N-petal rose) calibration manoeuvre.
 *
 * Sampling a rose curve gives a smooth closed path that presents many headings
 * and roll angles to the magnetometer. Used for calibration flights.
 */
export type CloverleafPattern = { 
/**
 * Centre of the manoeuvre.
 */
center: GeoPoint, 
/**
 * Petal reach from the centre, metres.
 */
radius_m: number, 
/**
 * Petal count; 4 is a cloverleaf, must be even and >= 4.
 */
petals: number, 
/**
 * Waypoints sampled per petal.
 */
samples_per_petal: number, 
/**
 * Constant planned altitude, metres AMSL.
 */
altitude_amsl_m: number, 
/**
 * Rotation of the whole pattern, degrees clockwise from north.
 */
start_heading_deg: number, 
/**
 * Ground speed change emitted once at the start, if any.
 */
speed_mps: number | null, };
