// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The frame a plan is compiled to.
 */
export type FramePolicy = "global_int" | "global_relative_alt_int";
