// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Horizontal position in WGS84 degrees.
 *
 * Height is deliberately absent: an absolute height is always
 * [`crate::height::Height`], carried by the waypoint's `altitude`.
 */
export type GeoPoint = { latitude_deg: number, longitude_deg: number, };
