// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Autopilot } from "./Autopilot";
import type { BaseMode } from "./BaseMode";
import type { FlightState } from "./FlightState";
import type { VehicleType } from "./VehicleType";

/**
 * Normalized `HEARTBEAT`.
 */
export type Heartbeat = { system_id: number, component_id: number, vehicle_type: VehicleType, autopilot: Autopilot, base_mode: BaseMode, custom_mode: number, flight_state: FlightState, mavlink_version: number, };
