// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { HeightDatum } from "./HeightDatum";

/**
 * A datum-tagged absolute height in meters.
 */
export type Height = { datum: HeightDatum, meters: number, };
