// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Height datum tags.
 */
export type HeightDatum = "ELLIPSOID_WGS84" | "AMSL_EGM96" | "ORTHOMETRIC_CGVD2013";
