// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What a group of pattern waypoints represents.
 */
export type LineKind = "survey" | "tie" | "calibration";
