// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Link state reported by the worker.
 */
export type LinkState = "connecting" | "connected" | "reconnecting" | "disconnected";
