// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MissionFrame } from "./MissionFrame";

/**
 * A single mission item (MISSION_ITEM_INT payload).
 *
 * `x`/`y` are the raw MAVLink integers (lat/lon ×1e7 for global frames, local
 * meters ×1e4 for local frames); `z` is the altitude in meters.
 */
export type MissionItem = { 
/**
 * Waypoint sequence number, zero-based.
 */
seq: number, frame: MissionFrame, 
/**
 * MAV_CMD value (e.g. 16 = NAV_WAYPOINT).
 */
command: number, 
/**
 * Command parameters P1..P4.
 *
 * For an integer mission item P5/P6/P7 are the coordinate fields, which
 * live in `x`/`y`/`z`; duplicating them here would lose precision when the
 * `i32` lat/lon is narrowed to `f32` (issues.md #10).
 */
params: Array<number>, x: number, y: number, z: number, autocontinue: boolean, 
/**
 * Whether this item is the active one (1 for the first item on upload).
 */
current: boolean, };
