// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MissionItem } from "./MissionItem";

/**
 * An in-memory mission.
 */
export type Mission = { items: Array<MissionItem>, 
/**
 * Currently active waypoint sequence, if any.
 */
current_seq: number | null, };
