// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LineKind } from "./LineKind";

/**
 * One flown line: a contiguous `seq` range plus its length.
 *
 * The post-flight tools segment the ULog mission-seq topic with this table, so
 * no hardware line markers are needed.
 */
export type PatternLine = { 
/**
 * 1-based line number within its kind.
 */
id: number, kind: LineKind, 
/**
 * First waypoint sequence, inclusive.
 */
start_seq: number, 
/**
 * Last waypoint sequence, inclusive.
 */
end_seq: number, length_m: number, };
