// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Height } from "./Height";
import type { PlanBlock } from "./PlanBlock";
import type { PlanMeta } from "./PlanMeta";
import type { PlannedWaypoint } from "./PlannedWaypoint";

/**
 * A mission as planned, before it is compiled to the wire frames.
 */
export type PlannedMission = { 
/**
 * HOME reference in AMSL; the origin of the relative frame.
 */
home: Height, 
/**
 * Planned waypoints in flyable order.
 */
waypoints: Array<PlannedWaypoint>, 
/**
 * Opaque QGC complex items kept for round-trip provenance.
 */
blocks: Array<PlanBlock>, meta: PlanMeta, };
