// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * An opaque QGC complex item (Survey, Corridor Scan, ...).
 *
 * The generated waypoints are compiled into [`PlannedMission::waypoints`];
 * the block itself is kept verbatim so a QGC plan survives a round trip
 * (ADR-003, issues.md #12).
 */
export type PlanBlock = { 
/**
 * QGC complex-item type, e.g. `Survey`.
 */
kind: string, 
/**
 * Original JSON fragment, preserved byte-for-byte.
 */
raw_json: string, };
