// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * How a serial port is attached to the host.
 */
export type PortTransport = "usb" | "pci" | "bluetooth" | "virtual" | "unknown";
