// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SignalId } from "./SignalId";

/**
 * One collected numeric sample.
 */
export type SignalSample = { id: SignalId, 
/**
 * Host-aligned time in milliseconds (see `tap::TimestampPolicy`).
 */
t_ms: number, value: number, };
