// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A spectrum computed by an [`Analyzer`] over one window.
 */
export type SpectrumFrame = { 
/**
 * Assumed sample rate, Hz.
 */
fs: number, 
/**
 * FFT length (power of two).
 */
n: number, 
/**
 * Bin width, Hz (`fs / n`).
 */
delta_f: number, 
/**
 * Nyquist frequency, Hz.
 */
nyquist: number, 
/**
 * One value per bin (magnitude, PSD or dB per the analyzer scale).
 */
bins: Array<number>, 
/**
 * Index of the strongest bin.
 */
peak_bin: number, 
/**
 * Frequency of the strongest bin, Hz.
 */
peak_freq_hz: number, 
/**
 * Value of the strongest bin.
 */
peak_value: number, };
