// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { GeoPoint } from "./GeoPoint";

/**
 * A parallel-line survey sweep, optionally with perpendicular tie lines.
 *
 * Lines are clipped to the polygon, so the flown extent is the polygon itself.
 * `alternate` flies a serpentine (each line reversed) instead of returning to
 * the start of every line; for magnetic data a unidirectional sweep can be
 * preferable, so both are supported.
 */
export type SurveyPattern = { 
/**
 * Survey area; must be convex and simple (MVP line clipper).
 */
polygon: Array<GeoPoint>, 
/**
 * Sweep direction, degrees clockwise from north.
 */
line_azimuth_deg: number, 
/**
 * Distance between adjacent sweep lines, metres.
 */
line_spacing_m: number, 
/**
 * Distance between tie lines, metres. `None` = no tie lines.
 */
tie_spacing_m: number | null, 
/**
 * Tie-line direction, degrees clockwise from north (usually perpendicular).
 */
tie_azimuth_deg: number, 
/**
 * Straight run added before the first waypoint of each line, metres.
 */
lead_in_m: number, 
/**
 * Straight run added after the last waypoint of each line, metres.
 */
lead_out_m: number, 
/**
 * Constant planned altitude, metres AMSL (draping is WS-D).
 */
altitude_amsl_m: number, 
/**
 * Serpentine (alternating line direction) when true.
 */
alternate: boolean, 
/**
 * Ground speed change emitted once at the start, if any.
 */
speed_mps: number | null, };
