// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Epoch-ms timestamp of the last update per telemetry field.
 *
 * `None` means the field has not been seen since connecting.
 */
export type TelemetryFieldAges = { heartbeat_at_ms: number | null, global_position_at_ms: number | null, attitude_at_ms: number | null, sys_status_at_ms: number | null, battery_at_ms: number | null, gps_at_ms: number | null, };
