// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AlgoConfig } from "./AlgoConfig";
import type { AnalyzerSource } from "./AnalyzerSource";
import type { SignalId } from "./SignalId";

/**
 * The full configuration of one plotted trace: a stable id, the source signal
 * plus the filter chain and optional analyzer to apply to it. Several traces
 * may bind the same signal with different filters.
 */
export type Trace = { 
/**
 * Stable identity within one plot window (see [`TraceId`]).
 */
id: string, signal: SignalId, 
/**
 * Ordered filter stages applied to every sample (`detrend → LPF`).
 */
pipeline: Array<AlgoConfig>, 
/**
 * An optional windowed analyzer (the FFT) on the raw signal.
 */
analyzer: AlgoConfig | null, 
/**
 * Whether the analyzer window sees the raw signal or the filtered output.
 */
analyzer_source: AnalyzerSource, };
