// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Vehicle/component type from `HEARTBEAT`.
 */
export type VehicleType = "generic" | "fixed_wing" | "quadrotor" | "coaxial" | "helicopter" | "tricopter" | "hexarotor" | "octorotor" | "dodecarotor" | "generic_multirotor" | "ground_rover" | "surface_boat" | "submarine" | "vtol_tailsitter_duorotor" | "vtol_tailsitter_quadrotor" | "vtol_tiltrotor" | "vtol_fixedrotor" | "vtol_tailsitter" | "vtol_tiltwing" | "gcs" | "antenna_tracker" | "onboard_controller" | "gimbal" | "camera" | "other" | "unknown";
