// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Identity of a MAVLink node: the `(system_id, component_id)` pair a frame
 * was sent from.
 *
 * Telemetry must be attributed to one vehicle: a link shared with QGroundControl,
 * a gimbal, a companion computer or a second airframe carries heartbeats and
 * telemetry from several nodes, and only the target FC's data belongs in the
 * snapshot (issue #6).
 */
export type VehicleId = { system_id: number, component_id: number, };
