// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 3D velocity in local NED frame, m/s.
 */
export type VelocityNed = { x_m_s: number, y_m_s: number, z_m_s: number, };
