// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AlgoKind } from "./AlgoKind";
import type { ParamSpec } from "./ParamSpec";

/**
 * Serializable algorithm description sent to the frontend.
 */
export type AlgorithmInfo = { id: string, name: string, kind: AlgoKind, params: Array<ParamSpec>, };
