// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One algorithm bound to parameters, as configured by the UI.
 */
export type AlgoConfig = { 
/**
 * A registry algorithm id (`lpf2`, `fft`, …).
 */
algorithm: string, 
/**
 * Parameter key/value pairs for that algorithm.
 */
params: Array<[string, number]>, };
