// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Autopilot type from `HEARTBEAT`.
 */
export type Autopilot = "generic" | "ardu_pilot" | "px4" | "open_pilot" | "auto_quad" | "smartap" | "generic_waypoints_only" | "generic_waypoints_and_simple_navigation_only" | "generic_mission_full" | "invalid" | "other" | "unknown";
