// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SignalId } from "./SignalId";

/**
 * One row of the signal tree.
 */
export type CatalogEntry = { signal: SignalId, 
/**
 * MAVLink message name (`ATTITUDE`, `HIGHRES_IMU`, …), from
 * `mavlink_core::Message::message_name`. Lets the signal tree group and
 * label without a hand-maintained id → name map.
 */
message_name: string, last_value: number, 
/**
 * EMA of the arrival rate, Hz.
 */
rate_hz: number, 
/**
 * Host time of the last sample, ms.
 */
last_seen_ms: number, };
