// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SignalId } from "./SignalId";

/**
 * One row of the signal tree.
 */
export type CatalogEntry = { signal: SignalId, last_value: number, 
/**
 * EMA of the arrival rate, Hz.
 */
rate_hz: number, 
/**
 * Host time of the last sample, ms.
 */
last_seen_ms: number, };
