// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Suggested role for a recognized device (plan §9).
 */
export type DeviceRole = "flight_controller" | "rtk_base_station" | "other";
