// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * System status flag from `HEARTBEAT`.
 */
export type FlightState = "uninit" | "boot" | "calibrating" | "standby" | "active" | "critical" | "emergency" | "poweroff" | "flight_termination" | "unknown";
