// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Height } from "./Height";
import type { VelocityNed } from "./VelocityNed";

/**
 * Normalized `GLOBAL_POSITION_INT`.
 */
export type GlobalPositionInt = { 
/**
 * Milliseconds since boot of the sending system.
 */
time_boot_ms: number, latitude_deg: number, longitude_deg: number, 
/**
 * AMSL altitude as reported by PX4 (datum-tagged per ADR-006).
 */
altitude: Height, 
/**
 * Height above home, meters (a delta, not a datum height).
 */
relative_alt_m: number, velocity: VelocityNed, 
/**
 * Yaw in degrees (0 = north, clockwise).
 */
heading_deg: number, };
