// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * GPS fix quality, driving the RTK status bar (plan §8).
 */
export type GpsFixType = "NO_GPS" | "NO_FIX" | "FIX2D" | "FIX3D" | "DGPS" | "RTK_FLOAT" | "RTK_FIXED" | "STATIC";
