// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { GpsFixType } from "./GpsFixType";
import type { Height } from "./Height";

/**
 * Normalized `GPS_RAW_INT`.
 */
export type GpsRawInt = { fix_type: GpsFixType, satellites_visible: number, latitude_deg: number, longitude_deg: number, 
/**
 * AMSL altitude (datum-tagged per ADR-006).
 */
altitude: Height, hdop: number, vdop: number, velocity_m_s: number, course_over_ground_deg: number, };
