// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Clone-friendly classification of a link failure (the underlying
 * `MavlinkError` is not `Clone`, so events carry this summary).
 */
export type LinkErrorKind = "io" | "serial" | "protocol" | "heartbeat_timeout" | "invalid_endpoint" | "other";
