// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LinkState } from "./LinkState";

/**
 * Desktop/headless bridge: a snapshot of the MAVLink link status emitted
 * to the frontend alongside telemetry.
 */
export type LinkStatus = { link_state: LinkState, endpoint: string, 
/**
 * True when a target-FC heartbeat was seen recently.
 */
fc_alive: boolean, };
