// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Coordinate frame of a mission item.
 *
 * Only the integer (`*_INT`) global frames are modelled: a mission item is
 * always exchanged as `MISSION_ITEM_INT`, so keeping both the INT and
 * non-INT spelling made download→upload round trips lossy (issues.md #11).
 */
export type MissionFrame = "global_int" | "global_relative_alt_int" | "global_terrain_alt_int" | "local_ned" | "local_enu" | "local_offset_ned" | "body_ned";
