// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * How a parameter is edited and validated.
 */
export type ParamKind = { "kind": "float", min: number, max: number, step: number, log: boolean, } | { "kind": "int", min: bigint, max: bigint, } | { "kind": "enum", options: Array<string>, } | { "kind": "bool" };
