// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ParamKind } from "./ParamKind";

/**
 * One editable parameter of an algorithm, as sent to the frontend.
 */
export type ParamSpec = { key: string, label: string, unit: string | null, kind: ParamKind, default: number, };
