// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PatternLine } from "./PatternLine";
import type { PlannedWaypoint } from "./PlannedWaypoint";

/**
 * Generated waypoints plus the line table that indexes them.
 */
export type PatternPlan = { waypoints: Array<PlannedWaypoint>, lines: Array<PatternLine>, };
