// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { GeoPoint } from "./GeoPoint";
import type { Height } from "./Height";

/**
 * One planned waypoint: a horizontal position plus an absolute AMSL altitude.
 */
export type PlannedWaypoint = { position: GeoPoint, 
/**
 * Absolute altitude; must be [`HeightDatum::AmslEgm96`] to compile.
 */
altitude: Height, 
/**
 * MAV_CMD value (e.g. 16 = `NAV_WAYPOINT`).
 */
command: number, 
/**
 * Command parameters P1..P4.
 */
params: [number, number, number, number], autocontinue: boolean, };
