// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Trace } from "./Trace";

/**
 * One plot window: a stable id, a title, and the traces drawn on it.
 */
export type Plot = { id: string, title: string, traces: Array<Trace>, };
