// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Sensor present/enabled/health bitmasks from `SYS_STATUS`.
 */
export type SensorHealthMasks = { present: number, enabled: number, health: number, };
