// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DeviceId } from "./DeviceId";
import type { PortTransport } from "./PortTransport";

/**
 * A serial port discovered on the host, with identity metadata.
 */
export type SerialDeviceInfo = { 
/**
 * OS port name, e.g. `/dev/ttyUSB0` or `COM3`.
 */
port_name: string, 
/**
 * How the port is attached.
 */
transport: PortTransport, 
/**
 * VID/PID when available (USB).
 */
device_id: DeviceId | null, 
/**
 * USB serial number when the device provides one.
 */
serial_number: string | null, 
/**
 * Manufacturer string.
 */
manufacturer: string | null, 
/**
 * Product string.
 */
product: string | null, };
