// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Identifies one numeric signal: a field of a message type from one node.
 *
 * Array fields are expanded to one signal per element, `field[i]`; messages
 * with a string `name` field (`NAMED_VALUE_FLOAT`, `DEBUG_*`) use the name as
 * the field (`NAMED_VALUE_FLOAT/<name>`).
 */
export type SignalId = { system_id: number, component_id: number, 
/**
 * MAVLink message id.
 */
message_id: number, 
/**
 * Field path within the message, e.g. `"roll"` or `"accel[0]"`.
 */
field: string, };
