// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Output scale for the spectrum bins.
 */
export type SpectrumScale = "magnitude" | "psd" | "decibels";
