// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SensorHealthMasks } from "./SensorHealthMasks";

/**
 * Normalized `SYS_STATUS`.
 */
export type SysStatus = { sensors: SensorHealthMasks, 
/**
 * Main battery voltage in millivolts.
 */
battery_voltage_mv: number, 
/**
 * Main battery current in milliamps (signed).
 */
battery_current_ma: number, 
/**
 * Battery remaining percent (0–100).
 */
battery_remaining_percent: number, };
