// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Attitude } from "./Attitude";
import type { BatteryStatus } from "./BatteryStatus";
import type { GlobalPositionInt } from "./GlobalPositionInt";
import type { GpsRawInt } from "./GpsRawInt";
import type { SysStatus } from "./SysStatus";

/**
 * Combined telemetry snapshot published to the UI (e.g. at 10–30 Hz).
 */
export type TelemetrySnapshot = { 
/**
 * Monotonic ms timestamp of the latest HEARTBEAT from the FC.
 */
last_heartbeat_at_ms: bigint | null, global_position: GlobalPositionInt | null, attitude: Attitude | null, sys_status: SysStatus | null, battery: BatteryStatus | null, gps: GpsRawInt | null, };
