// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LinkErrorKind } from "./LinkErrorKind";

/**
 * A link-layer error surfaced to the UI.
 *
 * Carries the failure category and a timestamp so the UI can show an error
 * history instead of a single overwritten string (issues.md #17).
 */
export type TelemetryError = { kind: LinkErrorKind, message: string, at_ms: number, };
