// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SignalId } from "./SignalId";

/**
 * One processed sample streamed to the inspector window.
 */
export type TraceSample = { id: SignalId, 
/**
 * Host-aligned time in milliseconds.
 */
t_ms: number, raw: number, 
/**
 * Filtered value; `NaN` when the trace has no pipeline or across a gap.
 */
filtered: number, };
