// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AlgoConfig } from "./AlgoConfig";
import type { SignalId } from "./SignalId";

/**
 * The full configuration of one plotted trace: the source signal plus the
 * filter chain and optional analyzer to apply to it.
 */
export type TraceConfig = { signal: SignalId, 
/**
 * Ordered filter stages applied to every sample (`detrend → LPF`).
 */
pipeline: Array<AlgoConfig>, 
/**
 * An optional windowed analyzer (the FFT) on the raw signal.
 */
analyzer: AlgoConfig | null, };
