// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Windowing functions available to the analyzer.
 */
export type WindowKind = "rectangular" | "hann" | "hamming" | "blackman" | "flat_top";
